### ISSUE TITLE
Statement modifiers conversion

### ISSUE THREAD

**Issue by cjelli** [Camelcade/Perl5-IDEA#1604] opened 2017-10-26 22:08 UTC
Hi guys,

Very nice module, almost switched from Emacs to IDEA thanks to it. 
I'd like to place a feature request.
One feature I use quite a lot from the CPerl module in Emacs that is lacking is the ability to convert a statement modifier into a code block and vice versa, e.g.
```
    print "some string\n" if $variable == 1;
```
Move the cursor under the "if"
Press C-c C-t
Get:
```
    if ($variable == 1) {
        print "some string\n";
    }
```
Then, if you move the cursor under the if again and press C-c C-t again, you get the statement modifier syntax back.
Thanks!

**Comment by hurricup** [comment] 2017-10-27 19:03
Btw, duplicate of #136

**Comment by hurricup** [comment] 2017-10-30 18:48
I've made a direct conversion statement with modifier => compound. Feel free to build plugin and check it out. Use intention with `Alt + Enter`
See README with building instructions

**Closed** 2017-11-04 19:57 UTC
Labels: Intentions
