### ISSUE TITLE
Moo and IntelliJ IDEA 2021.1 RC

### ISSUE THREAD

**Issue by targzeta** [Camelcade/Perl5-IDEA#2352] opened 2021-04-02 15:15 UTC
With the new RC 2021.1 the 'has' pragma is not found. See this:

![screenshot_20210402_170447](https://user-images.githubusercontent.com/2431105/113428162-98286280-93d6-11eb-9ddb-6bbb159e9df4.jpg)

I'm using this Dokerfile:
```
FROM centos:8

RUN yum install -y \
        gcc \
        perl \
        perl-App-cpanminus \
        perl-Data-Dump \
        perl-Module-Build \
        perl-Module-Runtime \
        perl-parent \
        which \
        wget \
    && yum clean all

ENV LC_ALL=C

RUN cpanm \
        Config::Any@0.32 \
        File::Share@0.25 \
        File::Slurp@9999.32 \
        Hash::Merge@0.302 \
        Log::Log4perl@1.54 \
        Moo@2.005004 \
        MooX::late@0.100 \
        MooX::Options@4.103 \
        MooX::Singleton@1.20 \
        namespace::autoclean@0.29 \
        Net::Server@2.010 \
    && rm -rf /root/.cpanm
```

Thank you in advance,
Emanuele

**Comment by sirtoobii** [comment] 2021-04-21 09:18
This is probably a duplicate of #2238

**Comment by hurricup** [comment] 2021-04-21 09:28
Does this happen in local case or only in Docker?

**Comment by targzeta** [comment] 2021-04-21 09:44
I made a test. It happens also with local perl:
![screenshot_20210421_114022](https://user-images.githubusercontent.com/2431105/115533003-9bf12b80-a296-11eb-80f8-4277d9c43ce0.jpg)

**Comment by EinsKay** [comment] 2021-04-21 10:06
I am using local perl 5.32.0 and Moose, the referenced #2238 above is open for months now. Makes working with error/warning highlighting quite a pain.

**Comment by hurricup** [comment] 2021-04-21 10:31
Sorry, had no time to fix all things. Will try to address this ASAP

**Comment by targzeta** [comment] 2021-04-21 11:10
So, the problem is not related to the new release of IntelliJIDEA. Said this, I really appreciate your work, @hurricup. I can wait for this fix :wink:!

Best regards,
Emanuele

**Comment by hurricup** [comment] 2021-04-21 14:32
So. `has` has no some clear definition, but defined with some perl magic. You are saying it happens with new rc. Has it ever worked? And if yes:
1. In which version?
2. Where navigation led?

**Comment by hurricup** [comment] 2021-04-21 14:35
I can't be sure, but in some version i've changed `has` from being keyword to be a sub call (as it is). So previously it had no reference at all. Probably this is the cause of the problem.

**Comment by targzeta** [comment] 2021-04-21 14:50
> So. `has` has no some clear definition, but defined with some perl magic. You are saying it happens with new rc. Has it ever worked? And if yes:
> 
>     1. In which version?
> 
>     2. Where navigation led?

No, I'm not sure it workerd before.

**Comment by EinsKay** [comment] 2021-04-21 14:51
Honestly I cannot contribute to the behavior regarding `Moo`. I can say `has` worked for me for `Moose` around May 2020 - when I bought my IJ license just because of your excellent Perl support :-)
In summer 2020 it started being shown as unknown.
Unfortunately, I switched from Perl 5.24 to 5.30 in early summer as well.
Still, the IDE recognizes the attributes themselves in the code quite nicely.

**Comment by sirtoobii** [comment] 2021-04-21 15:05
> Unfortunately, I switched from Perl 5.24 to 5.30 in early summer as well.
It is most likely not linked to a specific Perl version. For me the issue is apparent on version 5.22, 5.26 and 5.32

**Comment by hurricup** [comment] 2021-04-21 15:30
- [x] Fix exports for `Moose`
- [ ] Ensure `Moose::Role`, `MooseX::Method::Attributes`,  `MooseX::*` export what they do
- [ ] Fix exports for `Moo`

**Comment by hurricup** [comment] 2021-04-21 15:31
Ok, build from https://github.com/Camelcade/Perl5-IDEA/actions/runs/771181621 should work fine with `Moose`. Will try to fix `Moo` tomorrow

**Comment by targzeta** [comment] 2021-04-21 16:06
@hurricup do you do some class inspection to find functions and methods? This simple script seems work fine to get a list of the things we can use when we load some module:
```perl
#!/usr/bin/perl
use strict;
use warnings;

use Data::Dumper;
use Class::Inspector;
use Module::Load;

my $pkg = 'Moo';
autoload($pkg);

print "$pkg functions: " . Dumper(Class::Inspector->functions($pkg));
print "$pkg methods: " . Dumper(Class::Inspector->methods($pkg));

print "main functions: " . Dumper(Class::Inspector->functions('main'));
print "main methods: " . Dumper(Class::Inspector->methods('main'));
```
I don't know if is it possible to execute this type of script. I don't know how and when we can execute this, specially whithin Docker (I use Docker only). But it can resolves all the magic things. For example if you use `File::Spec` you have:
```
File::Spec methods: $VAR1 = [
      ...
          'abs2rel',
          'canonpath',
          'case_tolerant',
          'catdir',
          'catfile',
          'catpath',
          'curdir',
          'devnull',
          'file_name_is_absolute',
          'join',
          'no_upwards',
          'path',
          'rel2abs',
          'rootdir',
          'splitdir',
          'splitpath',
          'tmpdir',
          'updir'
        ];
```
So File::Spec->catfile() is now resolved. We can't jump to the code, obviously.

Again, if we use Moo and we have this line:
`has test => (is => 'rwp', predicate => 1, clearer => 1);`
we have:
```
main methods: $VAR1 = [
...
          '_set_test',
          'clear_test',
          'has_test',
        ];
```
So is it allowed to write `$self->_set_test()`.

What do you think about?
Emanuele

**Comment by hurricup** [comment] 2021-04-21 17:39
@targzeta such approach used for XS deparsing. But it's very bad for sources. Imagine huge project and some files declaring multiple subs in different namespaces. This means we should re-run this script for each file on each change.

Basically plugin extracts some information from each file and keeps it in some serialized binary format. When file changes, we only updating this file's data. And when you are using plugin, it tries to infer what subs are defined and where. In some cases this is possible and sometimes - not. 

For popular libs we may help by hardcoding some tricky exports, like I did for `Moose`. I attempted to introduce external annotations to give user the way to make like declarations files. But never finished. Will try again at some point. 

You may use the script above for your library code and generate fake perl file with subs declarations. In such case subs gonna be resolved and navigated to your fake file. But this is not the way I want to go in general. I'm teaching plugin to understand perl and what it does iteratively. So it's becoming better but never be perfect :)

**Comment by hurricup** [comment] 2021-04-25 16:18
```
#use Moose;

Parents:
        Moose::Object

Subs:
        after   =>      Moose::after (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        around  =>      Moose::around (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        augment =>      Moose::augment (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        before  =>      Moose::before (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        blessed =>      Scalar::Util::blessed (undefined, undefined)
        confess =>      Carp::confess (/home/hurricup/perl5/perlbrew/perls/perl-5.32.0/lib/5.32.0/Carp.pm, 292)
        extends =>      Moose::extends (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        has     =>      Moose::has (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        inner   =>      Moose::inner (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose.pm, 111)
        meta    =>      Test::Namespace::meta (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Class/MOP/Method/Meta.pm, 42)
        override        =>      Moose::override (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        super   =>      Moose::super (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose.pm, 94)
        with    =>      Moose::with (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
```

```
# use Moose::Role;

Parents:

Subs:
        after   =>      Moose::Role::after (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        around  =>      Moose::Role::around (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        augment =>      Moose::Role::augment (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 91)
        before  =>      Moose::Role::before (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        blessed =>      Scalar::Util::blessed (undefined, undefined)
        confess =>      Carp::confess (/home/hurricup/perl5/perlbrew/perls/perl-5.32.0/lib/5.32.0/Carp.pm, 292)
        excludes        =>      Moose::Role::excludes (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        extends =>      Moose::Role::extends (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 21)
        has     =>      Moose::Role::has (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        inner   =>      Moose::Role::inner (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 87)
        meta    =>      Test::Namespace::meta (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Class/MOP/Method/Meta.pm, 42)
        override        =>      Moose::Role::override (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        requires        =>      Moose::Role::requires (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        super   =>      Moose::Role::super (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 76)
        with    =>      Moose::Role::with (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
```

```
# use MooseX::MethodAttributes::Role;

Parents:

Subs:
        MODIFY_CODE_ATTRIBUTES  =>      MooseX::MethodAttributes::Role::AttrContainer::MODIFY_CODE_ATTRIBUTES (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/MooseX/MethodAttributes/Role/AttrContainer.pm, 20)
        after   =>      Moose::Role::after (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        around  =>      Moose::Role::around (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        augment =>      Moose::Role::augment (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 91)
        before  =>      Moose::Role::before (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        blessed =>      Scalar::Util::blessed (undefined, undefined)
        confess =>      Carp::confess (/home/hurricup/perl5/perlbrew/perls/perl-5.32.0/lib/5.32.0/Carp.pm, 292)
        excludes        =>      Moose::Role::excludes (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        extends =>      Moose::Role::extends (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 21)
        has     =>      Moose::Role::has (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        inner   =>      Moose::Role::inner (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 87)
        meta    =>      Test::Namespace::meta (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Class/MOP/Method/Meta.pm, 42)
        override        =>      Moose::Role::override (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        requires        =>      Moose::Role::requires (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        super   =>      Moose::Role::super (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 76)
        with    =>      Moose::Role::with (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
```

```
# use MooseX::Role::WithOverloading;

Parents:

Subs:
        after   =>      Moose::Role::after (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        around  =>      Moose::Role::around (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        augment =>      Moose::Role::augment (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 91)
        before  =>      Moose::Role::before (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        blessed =>      Scalar::Util::blessed (undefined, undefined)
        confess =>      Carp::confess (/home/hurricup/perl5/perlbrew/perls/perl-5.32.0/lib/5.32.0/Carp.pm, 292)
        excludes        =>      Moose::Role::excludes (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        extends =>      Moose::Role::extends (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 21)
        has     =>      Moose::Role::has (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        inner   =>      Moose::Role::inner (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 87)
        meta    =>      Test::Namespace::meta (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Class/MOP/Method/Meta.pm, 42)
        override        =>      Moose::Role::override (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        requires        =>      Moose::Role::requires (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        super   =>      Moose::Role::super (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 76)
        with    =>      Moose::Role::with (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
```

```
use MooseX::MethodAttributes;

Parents:
        Moose::Meta::Class::__ANON__::SERIAL::4

Subs:
        after   =>      Moose::after (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        around  =>      Moose::around (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        augment =>      Moose::augment (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        before  =>      Moose::before (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        blessed =>      Scalar::Util::blessed (undefined, undefined)
        confess =>      Carp::confess (/home/hurricup/perl5/perlbrew/perls/perl-5.32.0/lib/5.32.0/Carp.pm, 292)
        extends =>      Moose::extends (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        has     =>      Moose::has (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        inner   =>      Moose::inner (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose.pm, 111)
        meta    =>      Test::Namespace::meta (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Class/MOP/Method/Meta.pm, 42)
        override        =>      Moose::override (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        super   =>      Moose::super (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose.pm, 94)
        with    =>      Moose::with (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
```

```
# use Moose::Util::TypeConstraints;

Parents:

Subs:
        as      =>      Moose::Util::TypeConstraints::as (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 410)
        class_type      =>      Moose::Util::TypeConstraints::class_type (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 352)
        coerce  =>      Moose::Util::TypeConstraints::coerce (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 393)
        duck_type       =>      Moose::Util::TypeConstraints::duck_type (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 368)
        enum    =>      Moose::Util::TypeConstraints::enum (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 419)
        find_type_constraint    =>      Moose::Util::TypeConstraints::find_type_constraint (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 296)
        from    =>      Moose::Util::TypeConstraints::from (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 415)
        inline_as       =>      Moose::Util::TypeConstraints::inline_as (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 413)
        match_on_type   =>      Moose::Util::TypeConstraints::match_on_type (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 492)
        maybe_type      =>      Moose::Util::TypeConstraints::maybe_type (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 360)
        message =>      Moose::Util::TypeConstraints::message (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 412)
        register_type_constraint        =>      Moose::Util::TypeConstraints::register_type_constraint (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 308)
        role_type       =>      Moose::Util::TypeConstraints::role_type (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 356)
        subtype =>      Moose::Util::TypeConstraints::subtype (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 329)
        type    =>      Moose::Util::TypeConstraints::type (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 318)
        union   =>      Moose::Util::TypeConstraints::union (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 453)
        via     =>      Moose::Util::TypeConstraints::via (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 416)
        where   =>      Moose::Util::TypeConstraints::where (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Util/TypeConstraints.pm, 411)
```

```
use MooseX::Types::CheckedUtilExports;

Parents:

Subs:
        as      =>      MooseX::Types::CheckedUtilExports::as (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 398)
        class_type      =>      MooseX::Types::CheckedUtilExports::class_type (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 398)
        coerce  =>      MooseX::Types::CheckedUtilExports::coerce (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 398)
        duck_type       =>      MooseX::Types::CheckedUtilExports::duck_type (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 398)
        enum    =>      MooseX::Types::CheckedUtilExports::enum (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 398)
        from    =>      MooseX::Types::CheckedUtilExports::from (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 398)
        maybe_type      =>      MooseX::Types::CheckedUtilExports::maybe_type (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 398)
        role_type       =>      MooseX::Types::CheckedUtilExports::role_type (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 398)
        subtype =>      MooseX::Types::CheckedUtilExports::subtype (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 398)
        type    =>      MooseX::Types::CheckedUtilExports::type (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 398)
```

```
# use MooseX::ClassAttribute;

Parents:

Subs:
        class_has       =>      MooseX::ClassAttribute::class_has (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
```

```
# use MooseX::Role::Parameterized;

Parents:

Subs:
        after   =>      Moose::Role::after (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        around  =>      Moose::Role::around (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        augment =>      Moose::Role::augment (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 91)
        before  =>      Moose::Role::before (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        blessed =>      Scalar::Util::blessed (undefined, undefined)
        confess =>      Carp::confess (/home/hurricup/perl5/perlbrew/perls/perl-5.32.0/lib/5.32.0/Carp.pm, 292)
        excludes        =>      Moose::Role::excludes (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        extends =>      Moose::Role::extends (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 21)
        has     =>      Moose::Role::has (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        inner   =>      Moose::Role::inner (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 87)
        meta    =>      Test::Namespace::meta (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Class/MOP/Method/Meta.pm, 42)
        method  =>      MooseX::Role::Parameterized::method (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        override        =>      Moose::Role::override (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        parameter       =>      MooseX::Role::Parameterized::parameter (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 398)
        requires        =>      Moose::Role::requires (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
        role    =>      MooseX::Role::Parameterized::role (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 398)
        super   =>      Moose::Role::super (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Role.pm, 76)
        with    =>      MooseX::Role::Parameterized::with (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/x86_64-linux/Moose/Exporter.pm, 418)
```

```
# use Moo;

Parents:
        Moo::Object

Subs:
        after   =>      Moo::after (/home/hurricup/Projects/Moo/lib/Moo.pm, 131)
        around  =>      Moo::around (/home/hurricup/Projects/Moo/lib/Moo.pm, 131)
        before  =>      Moo::before (/home/hurricup/Projects/Moo/lib/Moo.pm, 131)
        extends =>      Moo::extends (/home/hurricup/Projects/Moo/lib/Moo.pm, 98)
        has     =>      Moo::has (/home/hurricup/Projects/Moo/lib/Moo.pm, 108)
        with    =>      Moo::with (/home/hurricup/Projects/Moo/lib/Moo.pm, 103)
```

```
# use Role::Tiny;

Parents:

Subs:
        after   =>      Role::Tiny::__ANON__ (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/Role/Tiny.pm, 141)
        around  =>      Role::Tiny::__ANON__ (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/Role/Tiny.pm, 141)
        before  =>      Role::Tiny::__ANON__ (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/Role/Tiny.pm, 141)
        requires        =>      Role::Tiny::__ANON__ (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/Role/Tiny.pm, 148)
        with    =>      Role::Tiny::__ANON__ (/home/hurricup/.perlbrew/libs/perl-5.32.0@plugin_test/lib/perl5/Role/Tiny.pm, 152)
```

```
# use Moo::Role;

Parents:

Subs:
        after   =>      Moo::Role::after (/home/hurricup/Projects/Moo/lib/Moo/Role.pm, 102)
        around  =>      Moo::Role::around (/home/hurricup/Projects/Moo/lib/Moo/Role.pm, 102)
        before  =>      Moo::Role::before (/home/hurricup/Projects/Moo/lib/Moo/Role.pm, 102)
        has     =>      Moo::Role::has (/home/hurricup/Projects/Moo/lib/Moo/Role.pm, 83)
        meta    =>      Moo::Role::meta (/home/hurricup/Projects/Moo/lib/Moo/Role.pm, 127)
        requires        =>      Moo::Role::requires (/home/hurricup/Projects/Moo/lib/Moo/Role.pm, 108)
        with    =>      Moo::Role::with (/home/hurricup/Projects/Moo/lib/Moo/Role.pm, 112)
```

**Comment by targzeta** [comment] 2021-04-26 15:01
@hurricup the use of Role:Tiny (or Moo::Role) includes also the "use strict" and "use warnings". Currently, the plugin complains for these lacks.

Emanuele

**Closed** 2021-05-09 11:38 UTC

**Comment by targzeta** [comment] 2021-05-11 13:27
It works!
It doesn't recognize the magical subs, yet. But it works! Thank you @hurricup!!!

Emanuele

![screenshot_20210511_152337](https://user-images.githubusercontent.com/2431105/117822659-09c4bd80-b26d-11eb-860b-dd2fe2c086ab.jpg)

**Comment by targzeta** [comment] 2021-05-11 14:22
It doens't know the subs `_set`, `has_` and `clear_`. See this attachment, it should be clearer.
![screenshot_20210511_161607](https://user-images.githubusercontent.com/2431105/117831326-bd7d7b80-b274-11eb-85d9-451ec5d4580a.jpg)

**Comment by hurricup** [comment] 2021-05-11 14:33
Oh, I see. This is strange, because IRR it supposed to work too. I'll check.
