### ISSUE TITLE
Indentation Logic is inverted

### ISSUE THREAD

**Issue by ENM1989** [Camelcade/Perl5-IDEA#2328] opened 2020-12-03 12:13 UTC
- IDE Name, Version, Build: PhpStorm, 2020.2.4, #PS-202.8194.11
- Perl5 Plugin Version: 2020.2.4
- JRE Version: openjdk 14 2020-03-17
- Your OS: macOS Catalina, 10.15.7

Hi,

in a project, I have to use a Mac and do some coding for a legacy Perl codebase.

I wanted to intent some lines and wondered, why the IDE gives me tabs instead of spaces.

I checked the "Editor > Code Style > Perl5 > Tabs and Indents" and saw, that the option "Use tab character" was not checked.

When I check the option, I get spaces instead of tabs.
It looks like that the logic is inverted.

See also the tweet on this topic:
https://twitter.com/ENM1989/status/1334115511639154696

**Comment by hurricup** [comment] 2020-12-04 08:56
Looks like there is an IDE problem. Investigating.

**Comment by hurricup** [comment] 2020-12-04 09:33
I filled an issue https://youtrack.jetbrains.com/issue/IDEA-256932
Will close this for now, re-open if necessary. Looks like IDE problem to me.

**Closed by hurricup** 2020-12-04 09:33 UTC
Labels: Bug, Formatting

**Comment by hurricup** [comment] 2020-12-04 09:42
Seems it's not a bug. But a feature. Disable this setting: 

![image](https://user-images.githubusercontent.com/2811330/101147993-2d386c00-362e-11eb-9716-3573a8c8d8f7.png)

**Comment by ENM1989** [comment] 2020-12-04 10:13
Hi @hurricup,

I tried out to disable this option and it worked like you said.
Now, the option of the "tabs + spaces" works like expected.

Just one thought about this:
If the "Detect and use existing file indents for editing" option is enabled, then in my opinion the "tabs + spaces" option should have no effect and should be "grayed out" (the user can not change its value).

**Comment by hurricup** [comment] 2020-12-04 11:26
This is a question to IDE, not perl plugin. Works this way everywhere. Still, there is a case when it's not possible to detect indentation from existing document.
